Landing page improvements
FDio/site pull request #114
Opened 2021-11-22 11:56 UTC by sknat

This is a first shot at #112 visuals are preliminary, for the sake of discussion,

Signed-off-by: Nathan Skrzypczak <nathan.skrzypczak@gmail.com>

2021-11-22 11:59 UTC, sknat commented
@edwarnicke @nealtex01 took at really quick shot at #112 doing mostly the layouts.
- Icons are only fa-based for now as this was easier
- I didn't change the background contents yet
But I think it already gives a sense of the navigation

2021-11-22 13:20 UTC, edwarnicke commented
@sknat Good start :)  Next up the arrows between the icons?

@nealtex01 do you have a better source for icons?

2021-11-22 18:19 UTC, sknat commented
Can do, I didn't for now as it is a bit tedious to build it and make it reactive.
I'd say next steps would be better backgrounds & icons

2023-02-24 17:27 UTC, dwallacelf commented on content/community/_index.md
>  [![VPP Monthly](https://img.shields.io/badge/VPP%20Monthly-Second%20Tuesday%208am%20PT-blue.svg?style=plastic)](https://wiki.fd.io/view/VPP/Meeting#Meeting_Details)
VPP meeting is now bi-monthly and at different times.  I might make sense to remove the time of the meetings from these buttons to reduce the need to maintain them when they change.

We should also add a buttons the TSC Meeting:
TSC Meeting -> https://wiki.fd.io/view/TSC#Meeting_Schedule_and_Logistics

2023-02-24 17:29 UTC, dwallacelf commented on content/community/_index.md
>  [![vpp-dev Mailing List](https://img.shields.io/badge/Mailing%20List-vpp-blue.svg?style=plastic)](https://lists.fd.io/g/vpp-dev)
Plesae add a button for the TSC mailing list -> https://lists.fd.io/g/tsc

2023-02-24 17:33 UTC, dwallacelf commented on content/community/_index.md
>  [![IRC](https://www.irccloud.com/invite-svg?channel=%23fdio&hostname=web.libera.chat%2Fgamja&port=6697&ssl=1)](https://www.irccloud.com/invite?channel=%23fdio&hostname=web.libera.chat%2Fgamja&port=66
I'm not sure why we're forcing/advocating for the use of irccloud.com here since it requires an additional login/creds.  I think it would be more friendly simply use the url:  https://web.libera.chat

2023-02-24 17:35 UTC, dwallacelf requested changes
There is also a dead link on the HICN Documentation page:

Documentation -> HICN Documentation -> 'Blog post' : https://deploy-preview-114--fdio.netlify.app/latest/news/hicn

2023-02-27 12:07 UTC, sknat commented
Thanks @dwallacelf for the review, 
all your comments should be addressed. Also packaged an image folder cleanup.

2023-02-27 20:23 UTC, dwallacelf approved these changes

2023-02-27 20:24 UTC, merged

2023-05-11 21:10 UTC, SimardeepSingh1450 commented
@sknat @edwarnicke I have went through the files : https://docs.google.com/presentation/d/1OPqjiJYdtaEUjWqRYAk27ctbZg-OiZktSNF12hXq7J4/edit#slide=id.p
https://docs.google.com/presentation/d/1928l56YGFk9oBuWaAx0FRzZBUUnGnIJDOxb1qMzaj-c/edit#slide=id.g100f35f23ab_2_24
And can help i contribute in someway :smile:?

2023-05-25 09:43 UTC, sknat commented
Hi SimardeepSingh1450,

These documents are quite old, we've merged a refactoring of the fd.io<http://fd.io> website based on these two presentations.
I guess moving forward we should open a discussion - i.e. a new issue -  to prioritise future evolutions.

Cheers
-Nathan


On 11 May 2023, at 23:10, SimardeepSingh1450 ***@***.******@***.***>> wrote:



@sknat<https://github.com/sknat> @edwarnicke<https://github.com/edwarnicke> I have went through the files : https://docs.google.com/presentation/d/1OPqjiJYdtaEUjWqRYAk27ctbZg-OiZktSNF12hXq7J4/edit#slide=id.p
https://docs.google.com/presentation/d/1928l56YGFk9oBuWaAx0FRzZBUUnGnIJDOxb1qMzaj-c/edit#slide=id.g100f35f23ab_2_24
And can help i contribute in someway 😄?

—
Reply to this email directly, view it on GitHub<https://github.com/FDio/site/pull/114#issuecomment-1544685888>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAZ5XZFXUAJIVSQ7DZDQTYLXFVIWBANCNFSM5IQZSWZQ>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-05-25 19:14 UTC, SimardeepSingh1450 commented
@sknat Sure, I would like to contribute to some issues, or open some issues if i find some problem.