Upgrade to support new hugo releases.
FDio/site pull request #82
Opened 2020-12-10 18:40 UTC by otroan

Hugo from 0.60 upwards is CommonMark compliant.
Apparently that implies that HTML markup is considered unsafe.
Set unsafe=true for now.

After 0.56 symlinks to directories are not supported.
Using module.mounts instead.

Signed-off-by: Ole Troan <ot@cisco.com>

2020-12-15 15:21 UTC, edwarnicke commented
Big +1 on moving to module mounts, but it appears not to be working:

https://deploy-preview-82--fdio.netlify.app/docs/vpp/latest

2020-12-15 16:31 UTC, edwarnicke commented
https://deploy-preview-82--fdio.netlify.app/vppproject/vpptech/ 

![image](https://user-images.githubusercontent.com/1455208/102243361-b5393400-3ec0-11eb-83cb-d5d27170c7fa.png)


differs from  https://fd.io/vppproject/vpptech/

![image](https://user-images.githubusercontent.com/1455208/102243400-bff3c900-3ec0-11eb-9edd-7e2add23b580.png)

2020-12-15 16:33 UTC, edwarnicke commented
https://deploy-preview-82--fdio.netlify.app/community/join/

![image](https://user-images.githubusercontent.com/1455208/102243604-f92c3900-3ec0-11eb-9477-e18afed9df55.png)


differs from https://fd.io/community/join/

![image](https://user-images.githubusercontent.com/1455208/102243643-0517fb00-3ec1-11eb-89a6-b12f346aa469.png)

2020-12-15 16:36 UTC, edwarnicke requested changes

2020-12-15 16:36 UTC, edwarnicke commented on netlify.toml
> +HUGO_ENABLEGITINFO = "true"
Hold for fixes

2020-12-15 20:32 UTC, otroan commented on netlify.toml
> +HUGO_ENABLEGITINFO = "true"
I didn't add this line mind you. It was only git pointing out that it was lacking a newline at EOF.

2021-01-08 18:07 UTC, edwarnicke approved these changes

2021-01-08 18:07 UTC, merged