Transliteration of Technical Community Doc to Markdown
FDio/site pull request #90
Opened 2021-04-29 14:20 UTC by edwarnicke

Original: https://fd.io/docs/tsc/FD.IO-Technical-Community-Document-12-12-2017.pdf

This is an attempt to simply transfer formats from PDF to Markdown.
It should not change the contents of the document at all.

Signed-off-by: Ed Warnicke <hagbard@gmail.com>

2021-04-30 08:34 UTC, mdr78 requested changes
Good job Ed.

* 27 instances of double spacing - I annotated a few of these, but it is easier to do a find replace than me pointing out each one.
* I noted a few instances of double carriage return.
* There was one bullet formatting issue at the end of the document. 

Other than those, it is all good.

2021-04-30 08:34 UTC, mdr78 commented on content/community/tscdocs/technical_community_doc.md
> +  *This should include by which Milestone freezes of various sorts (for example
Need to fix bullet.

2021-04-30 08:34 UTC, mdr78 commented on content/community/tscdocs/technical_community_doc.md
> +trust.   Committers for a project select and vote for new Committers for that project,
Double space

2021-04-30 08:34 UTC, mdr78 commented on content/community/tscdocs/technical_community_doc.md
> +(the “Project”).  Capitalized terms not defined in the Technical Community
Double space

2021-04-30 08:34 UTC, mdr78 commented on content/community/tscdocs/technical_community_doc.md
> +Project.  The Technical Community Document may be amended from time to time by
Double space

2021-04-30 08:34 UTC, mdr78 commented on content/community/tscdocs/technical_community_doc.md
> +
Double carriage return

2021-04-30 08:34 UTC, mdr78 commented on content/community/tscdocs/technical_community_doc.md
> +
Double carriage return

2021-04-30 08:34 UTC, mdr78 commented on content/community/tscdocs/technical_community_doc.md
> +
Double carriage return

2021-04-30 08:34 UTC, mdr78 commented on content/community/tscdocs/technical_community_doc.md
> +
Double carriage return

2021-05-19 18:19 UTC, edwarnicke commented on content/community/tscdocs/technical_community_doc.md
> +trust.   Committers for a project select and vote for new Committers for that project,
This is a triple space.  Fixed :)

2021-05-19 18:22 UTC, edwarnicke commented on content/community/tscdocs/technical_community_doc.md
> +  *This should include by which Milestone freezes of various sorts (for example
Fixed

2021-05-19 18:23 UTC, edwarnicke commented on content/community/tscdocs/technical_community_doc.md
> +(the “Project”).  Capitalized terms not defined in the Technical Community
I still believe in the oxford comma and double spacing after a period :)

2021-05-19 18:23 UTC, edwarnicke commented on content/community/tscdocs/technical_community_doc.md
> +Project.  The Technical Community Document may be amended from time to time by
I still believe in the oxford comma and double spacing after a period :)

2021-05-19 18:23 UTC, edwarnicke commented on content/community/tscdocs/technical_community_doc.md
> +
I still believe in the oxford comma and double spacing after a period :)

2021-05-19 18:23 UTC, edwarnicke commented on content/community/tscdocs/technical_community_doc.md
> +
Fixed

2021-05-19 18:23 UTC, edwarnicke commented on content/community/tscdocs/technical_community_doc.md
> +
Fixed

2021-05-20 18:33 UTC, merged