Update documentation and feature list to 21.06.
FDio/site pull request #98
Opened 2021-07-20 11:49 UTC by otroan

Update master documentation link to latest.

Signed-off-by: Ole Troan <ot@cisco.com>

2021-07-20 11:56 UTC, edwarnicke commented
Could you rebase this onto the latest from master?

2021-07-20 12:06 UTC, ayourtch commented on static/docs/vpp/master/_static/documentation_options.js
> +    VERSION: 'master',
is this right that this is master as opposed to 21.06 ?

2021-07-20 12:07 UTC, ayourtch commented on static/docs/vpp/master/about.html
> +  <title>About &mdash; The Vector Packet Processor master documentation</title>
Same as above - master = what am I missing ?

2021-07-23 16:14 UTC, dwallacelf requested changes

2021-07-23 16:14 UTC, dwallacelf commented on content/vppProject/vppbuilding/vpp.md
> +	 "version 20.05, /docs/vpp/v2005/gettingstarted/developers"]
Same comment here.  Please remove 20.09 & 20.05

2021-07-23 16:14 UTC, dwallacelf commented on content/documentation/vpp.md
> +or [20.05](/docs/vpp/v2005).
The supported release versions include 21.06 & 21.01 per the historical release support policy.
Please remove versions 20.09 and 20.05 and add 21.01 in this list.

2021-07-23 16:19 UTC, dwallacelf requested changes
content/documentation/vpp.md, Line 16:  "The source code documentation is at [v21.01](https://docs.fd.io/vpp/21.01)."

s/01/06/g

2021-08-20 07:25 UTC, otroan commented on static/docs/vpp/master/_static/documentation_options.js
> +    VERSION: 'master',
This patch builds two document trees. One for master, one for 21.06. static/docs/vpp/master ...

2021-08-20 07:25 UTC, otroan commented on static/docs/vpp/master/about.html
> +  <title>About &mdash; The Vector Packet Processor master documentation</title>
Same as above

2021-08-21 08:29 UTC, merged